[package]
name = "rok-rinstall"
description = "Installation of R itself for rok"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
rok-core.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
flate2.workspace = true
tar.workspace = true
tempfile.workspace = true
